### ISSUE TITLE
fail to create I/O queue

### ISSUE THREAD

**Issue by clicx** [nvmedirect/nvmedirect#15]
nvmed_admin /dev/nvme0n1 set root 64
./nvmed_example /dev/nvme0n1

/proc/nvmed/nvme0n1/admin: fail to create I/O queue
Fail to create I/O queue

**Comment by ckaloger** [comment]
Hi,
i have the exact same issue
im working on centos 7 with 4.4 kernel 
help me out if solved

thanks

**Comment by cdcsl** [comment]
Hi.

Would you be able to tell me your CPU models and NVMe device models?

Thanks.

**Comment by ckaloger** [comment]
Hi,
cpu model is Intel Xeon E5520 and nvme device model is Samsung 950 Pro

**Comment by cdcsl** [comment]
@ckaloger, would you be able to run `nvmed_info /dev/nvme0n1 all | grep NSQA` as root and post the output?

Please change `/dev/nvme0n1` if it is different on your machine.

Thanks.

**Comment by hyeongjunkim** [comment]
@ckaloger,
You can't create I/O queues anymore, because kernel driver created all the I/O queues that your device supports. 
For your reference, Samsung 950 Pro has only 8 I/O queues.

To solve this problem, there is a way to reduce the number of queues generated by the kernel by modifying the kernel driver.

Based on the kernel 4.10, modify _nr_io_queues_ variables in _nvme_setup_io_queues()_ function.
from `nr_io_queues = num_online_cpus();`
to `nr_io_queues = 4;`  ( Any number you want to create in kernel space  )
https://elixir.bootlin.com/linux/v4.10/source/drivers/nvme/host/pci.c#L1408

Finally, I am sorry that my answer is toooooooo late.

**Comment by ckaloger** [comment]
thanks for the response even if too late as you said,
by the way ,i was working for my thesis in the university of Crete ,Greece
i was struggling with that topic (nvmedirect) for a long time so i finally gave up and chose something else  ,something easier so probably  is too late  for my case :p
