### ISSUE TITLE
Kernel errors

### ISSUE THREAD

**Issue by sudarsunkannan** [nvmedirect/nvmedirect#3]
Hello,

I tried using the example code after compiling and installing the driver. However, the queue creation fails pfnList = kzalloc(sizeof(__u64) * u_buf.size, GFP_KERNEL) and I get the following errors. Can you suggest what could be the problem?

[ 1873.252198]  [<ffffffff812d60b7>] dump_stack+0x6b/0xa4
[ 1873.257350]  [<ffffffff81066415>] warn_slowpath_common+0x95/0xe0
[ 1873.263354]  [<ffffffff8106647a>] warn_slowpath_null+0x1a/0x20
[ 1873.269182]  [<ffffffff81193877>] kzalloc
_slab+0x87/0xa0
[ 1873.274508]  [<ffffffff811cbe64>] _kzalloc+0x34/0x1c0
[ 1873.279658]  [<ffffffffa09bc66d>] ? nvmed_get_buffer_addr+0x4d/0x300 [nvmed]
[ 1873.286697]  [<ffffffff8119c801>] ? do_anonymous_page+0xf1/0x2d0
[ 1873.292694]  [<ffffffffa09bc66d>] nvmed_get_buffer_addr+0x4d/0x300 [nvmed]
[ 1873.299573]  [<ffffffff8109957c>] ? local_clock+0x1c/0x30
[ 1873.304980]  [<ffffffff810b3497>] ? __lock_release+0x3a7/0x480
[ 1873.310808]  [<ffffffffa09bd66b>] nvmed_admin_ioctl+0x16b/0x290 [nvmed]
[ 1873.317427]  [<ffffffff81113d80>] ? __audit_syscall_entry+0xb0/0x110
[ 1873.323780]  [<ffffffff8124dd7f>] proc_reg_unlocked_ioctl+0x3f/0x70
[ 1873.330046]  [<ffffffff811f2308>] vfs_ioctl+0x18/0x30
[ 1873.335090]  [<ffffffff811f2bd8>] do_vfs_ioctl+0x168/0x4b0
[ 1873.340575]  [<ffffffff81113d80>] ? __audit_syscall_entry+0xb0/0x110
[ 1873.346936]  [<ffffffff810af033>] ? up_read+0x23/0x40
[ 1873.351980]  [<ffffffff811f2fb2>] SyS_ioctl+0x92/0xa0
[ 1873.357041]  [<ffffffff8163d897>] entry_SYSCALL_64_fastpath+0x12/0x6f
[ 1873.363488] ---[ end trace 84c27705d065d208 ]---
[ 1873.368110] nvmed_get_buffer_addr pfnList failed

Thanks

**Comment by hyeongjunkim** [comment]
Sorry for the slow response.
Since you opened the issue, our library and kernel driver have been modified and uploaded several times.
Please test on latest framework and kernel drivers.
For your information, our framework only works in the vanilla kernel.
Not work correctly on customized kernel such as ubuntu, centos and fedora kernel.

First, I will close this issue.
If you still have problems on latest framework, please open a new Issue.

Thanks.
